{
    "image": "ubuntu:latest",
    "stages": [
        "build"
    ],
    "build_job": {
        "stage": "build",
        "script": [
            "apt update",
            "DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata",
            "apt install -y software-properties-common",
            "add-apt-repository ppa:mozillateam/ppa",
            "apt install -y bind9-host",
            "apt install -y curl",
            "apt install -y dbus-x11",
            "apt install -y dbus",
            "apt install -y dnsutils",
            "apt install -y firefox-esr",
            "apt install -y git",
            "apt install -y gpg",
            "apt install -y iproute2",
            "apt install -y iputils-ping",
            "apt install -y lsb-release",
            "apt install -y lsof",
            "apt install -y nano",
            "apt install -y net-tools",
            "apt install -y openssh-client",
            "apt install -y openssh-server",
            "apt install -y passwd",
            "apt install -y python3",
            "apt install -y snapd",
            "apt install -y squid",
            "apt install -y sudo",
            "apt install -y systemd-sysv",
            "apt install -y systemd",
            "apt install -y tigervnc-common",
            "apt install -y tigervnc-standalone-server",
            "apt install -y tightvncserver",
            "apt install -y tmate",
            "apt install -y tmux",
            "apt install -y unzip",
            "apt install -y wget",
            "apt install -y wireguard-tools",
            "apt install -y wireguard",
            "apt install -y x11vnc",
            "apt install -y xfce4-goodies",
            "apt install -y xfce4-session",
            "apt install -y xfce4",
            "apt install -y xrdp",
            "mkdir -p /root/.vnc/",
            "echo | vncpasswd -f > /root/.vnc/passwd",
            "chmod 600 /root/.vnc/passwd",
            "touch /root/.Xauthority",
            "echo 'unset SESSION_MANAGER' >> /root/.vnc/xstartup",
            "echo 'unset DBUS_SESSION_BUS_ADDRESS' >> /root/.vnc/xstartup",
            "echo 'startxfce4' >> /root/.vnc/xstartup",
            "chmod +x /root/.vnc/xstartup",
            "curl -L https://github.com/novnc/noVNC/archive/refs/tags/v1.6.0.zip -o /novnc.zip",
            "unzip /novnc.zip",
            "mv ./noVNC* /novnc",
            "printf '%s\\n' 'export USER=root' >> /root/.bashrc",
            "(/novnc/utils/novnc_proxy &) ; while sleep 0.1 ; do curl 127.0.0.1:6080 && break ; done",
            "mkdir -p /root/.ssh/",
            ":",
            "./to_be_launched_in_runner.sh"
        ]
    }
}
