{
    "name": "build",
    "on": {
        "push": {
            "branches": [
                "main"
            ]
        }
    },
    "jobs": {
        "build": {
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "uses": "actions/checkout@v4"
                },
                {
                    "name": "sudo apt update",
                    "run": "sudo apt update || apt update"
                },
                {
                    "name": "sudo apt update",
                    "run": "sudo apt install -y sudo || apt install -y sudo"
                },
                {
                    "name": "DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt-get -y install tzdata",
                    "run": "DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt-get -y install tzdata"
                },
                {
                    "name": "sudo apt install -y software-properties-common",
                    "run": "sudo apt install -y software-properties-common"
                },
                {
                    "name": "sudo add-apt-repository ppa:mozillateam/ppa",
                    "run": "sudo add-apt-repository ppa:mozillateam/ppa"
                },
                {
                    "name": "sudo apt install -y bind9-host",
                    "run": "sudo apt install -y bind9-host"
                },
                {
                    "name": "sudo apt install -y curl",
                    "run": "sudo apt install -y curl"
                },
                {
                    "name": "sudo apt install -y dbus-x11",
                    "run": "sudo apt install -y dbus-x11"
                },
                {
                    "name": "sudo apt install -y dbus",
                    "run": "sudo apt install -y dbus"
                },
                {
                    "name": "sudo apt install -y dnsutils",
                    "run": "sudo apt install -y dnsutils"
                },
                {
                    "name": "sudo apt install -y firefox-esr",
                    "run": "sudo apt install -y firefox-esr"
                },
                {
                    "name": "sudo apt install -y git",
                    "run": "sudo apt install -y git"
                },
                {
                    "name": "sudo apt install -y gpg",
                    "run": "sudo apt install -y gpg"
                },
                {
                    "name": "sudo apt install -y iproute2",
                    "run": "sudo apt install -y iproute2"
                },
                {
                    "name": "sudo apt install -y iputils-ping",
                    "run": "sudo apt install -y iputils-ping"
                },
                {
                    "name": "sudo apt install -y lsb-release",
                    "run": "sudo apt install -y lsb-release"
                },
                {
                    "name": "sudo apt install -y lsof",
                    "run": "sudo apt install -y lsof"
                },
                {
                    "name": "sudo apt install -y nano",
                    "run": "sudo apt install -y nano"
                },
                {
                    "name": "sudo apt install -y net-tools",
                    "run": "sudo apt install -y net-tools"
                },
                {
                    "name": "sudo apt install -y openssh-client",
                    "run": "sudo apt install -y openssh-client"
                },
                {
                    "name": "sudo apt install -y openssh-server",
                    "run": "sudo apt install -y openssh-server"
                },
                {
                    "name": "sudo apt install -y passwd",
                    "run": "sudo apt install -y passwd"
                },
                {
                    "name": "sudo apt install -y python3",
                    "run": "sudo apt install -y python3"
                },
                {
                    "name": "sudo apt install -y snapd",
                    "run": "sudo apt install -y snapd"
                },
                {
                    "name": "sudo apt install -y squid",
                    "run": "sudo apt install -y squid"
                },
                {
                    "name": "sudo apt install -y sudo",
                    "run": "sudo apt install -y sudo"
                },
                {
                    "name": "sudo apt install -y systemd-sysv",
                    "run": "sudo apt install -y systemd-sysv"
                },
                {
                    "name": "sudo apt install -y systemd",
                    "run": "sudo apt install -y systemd"
                },
                {
                    "name": "sudo apt install -y tigervnc-common",
                    "run": "sudo apt install -y tigervnc-common"
                },
                {
                    "name": "sudo apt install -y tigervnc-standalone-server",
                    "run": "sudo apt install -y tigervnc-standalone-server"
                },
                {
                    "name": "sudo apt install -y tightvncserver",
                    "run": "sudo apt install -y tightvncserver"
                },
                {
                    "name": "sudo apt install -y tmate",
                    "run": "sudo apt install -y tmate"
                },
                {
                    "name": "sudo apt install -y tmux",
                    "run": "sudo apt install -y tmux"
                },
                {
                    "name": "sudo apt install -y unzip",
                    "run": "sudo apt install -y unzip"
                },
                {
                    "name": "sudo apt install -y wget",
                    "run": "sudo apt install -y wget"
                },
                {
                    "name": "sudo apt install -y wireguard-tools",
                    "run": "sudo apt install -y wireguard-tools"
                },
                {
                    "name": "sudo apt install -y wireguard",
                    "run": "sudo apt install -y wireguard"
                },
                {
                    "name": "sudo apt install -y x11vnc",
                    "run": "sudo apt install -y x11vnc"
                },
                {
                    "name": "sudo apt install -y xfce4-goodies",
                    "run": "sudo apt install -y xfce4-goodies"
                },
                {
                    "name": "sudo apt install -y xfce4-session",
                    "run": "sudo apt install -y xfce4-session"
                },
                {
                    "name": "sudo apt install -y xfce4",
                    "run": "sudo apt install -y xfce4"
                },
                {
                    "name": "sudo apt install -y xrdp",
                    "run": "sudo apt install -y xrdp"
                },
                {
                    "name": "sudo apt install -y xxd",
                    "run": "sudo apt install -y xxd"
                },
                {
                    "name": "sudo apt install -y adb",
                    "run": "sudo apt install -y adb"
                },
                {
                    "name": "sudo apt install -y scrcpy",
                    "run": "sudo apt install -y scrcpy"
                },
                {
                    "name": "mkdir -p ~/.vnc/",
                    "run": "mkdir -p ~/.vnc/"
                },
                {
                    "name": "echo | vncpasswd -f | tee ~/.vnc/passwd > /dev/null",
                    "run": "echo | vncpasswd -f | tee ~/.vnc/passwd > /dev/null"
                },
                {
                    "name": "chmod 600 ~/.vnc/passwd",
                    "run": "chmod 600 ~/.vnc/passwd"
                },
                {
                    "name": "touch ~/.Xauthority",
                    "run": "touch ~/.Xauthority"
                },
                {
                    "name": "echo 'unset SESSION_MANAGER' | tee -a ~/.vnc/xstartup > /dev/null",
                    "run": "echo 'unset SESSION_MANAGER' | tee -a ~/.vnc/xstartup > /dev/null"
                },
                {
                    "name": "echo 'unset DBUS_SESSION_BUS_ADDRESS' | tee -a ~/.vnc/xstartup > /dev/null",
                    "run": "echo 'unset DBUS_SESSION_BUS_ADDRESS' | tee -a ~/.vnc/xstartup > /dev/null"
                },
                {
                    "name": "echo 'startxfce4' | tee -a ~/.vnc/xstartup > /dev/null",
                    "run": "echo 'startxfce4' | tee -a ~/.vnc/xstartup > /dev/null"
                },
                {
                    "name": "chmod +x ~/.vnc/xstartup",
                    "run": "chmod +x ~/.vnc/xstartup"
                },
                {
                    "name": "curl -L https://github.com/novnc/noVNC/archive/refs/tags/v1.6.0.zip -o ~/novnc.zip",
                    "run": "curl -L https://github.com/novnc/noVNC/archive/refs/tags/v1.6.0.zip -o ~/novnc.zip"
                },
                {
                    "name": "unzip ~/novnc.zip",
                    "run": "unzip ~/novnc.zip"
                },
                {
                    "name": "mv ./noVNC* ~/novnc",
                    "run": "mv ./noVNC* ~/novnc"
                },
                {
                    "name": "printf '%s\\n' 'export USER=$(whoami)' | tee -a ~/.bashrc > /dev/null",
                    "run": "printf '%s\\n' 'export USER=$(whoami)' | tee -a ~/.bashrc > /dev/null"
                },
                {
                    "name": "( ~/novnc/utils/novnc_proxy &) ; while sleep 0.1 ; do curl 127.0.0.1:6080 && break ; done",
                    "run": "( ~/novnc/utils/novnc_proxy &) ; while sleep 0.1 ; do curl 127.0.0.1:6080 && break ; done"
                },
                {
                    "name": "mkdir -p ~/.ssh/",
                    "run": "mkdir -p ~/.ssh/"
                },
                {
                    "name": ":",
                    "run": ":"
                },
                {
                    "name": "./to_be_launched_in_runner.sh",
                    "run": "./to_be_launched_in_runner.sh"
                }
            ]
        }
    }
}
