{
    "name": "build",
    "on": {
        "push": {
            "branches": [
                "main"
            ]
        }
    },
    "jobs": {
        "build": {
            "runs-on": "ubuntu-latest",
            "steps": [
                {
                    "uses": "actions/checkout@v4"
                },
                {
                    "name": "execute Dockerfile",
                    "run": "cat Dockerfile | grep -E '^RUN ' | cut -c 5-999999999 | bash -x"
                },
            ]
        }
    }
}
